language: node_js

node_js:
  - "node"

cache: npm

script: npm run build

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?$/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: client.zip
  skip_cleanup: true
  on:
    tags: true
